### ISSUE TITLE
Suggestion: on anvil gui open

### ISSUE THREAD

**Issue by ahmadmsaleem** [DereWah/Skript-AnvilGUI#1]
You have on anvil gui close and click event you are missing on open anvil gui event which can be very useful to have.

**Comment by DereWah** [comment]
Hey, thanks for the suggestion. Can you elaborate a bit more?

Right now opening an AnvilGUI anvil (which is a type that you have to construct by setting its items, default text and inventory name) can only be done via a line of code, therefore I don't think an event for when it's opened would be necessary.

Do you have any case usage where it could be useful?

**Comment by DereWah** [comment]
closing as not planned & no response from OP
