### ISSUE TITLE
An error is reported when the command is executed

### ISSUE THREAD

**Issue by CaesarGalahad** [DereWah/Skript-AnvilGUI#10]
Description
I loaded the sk file of AnvilGUI and Skript gets an error when I execute /openanvilgui

Server INFO
Server version purpur 2287 1.21.1
Skript version 2.9.1
Skript-AnvilGUI version 1.8

ErrorLOG
https://mclo.gs/63FP4fT

ServerFullLOG
https://mclo.gs/GNAvOIU

SK file
[AnvilGUi.zip](https://github.com/user-attachments/files/16623894/AnvilGUi.zip)

**Comment by Dere-Wah** [comment]
> Description
> I loaded the sk file of AnvilGUI and Skript gets an error when I execute /openanvilgui
> 
> Server INFO
> Server version purpur 2287 1.21.1
> Skript version 2.9.1
> Skript-AnvilGUI version 1.8
> 
> ErrorLOG
> https://mclo.gs/63FP4fT
> 
> ServerFullLOG
> https://mclo.gs/GNAvOIU
> 
> SK file
> [AnvilGUi.zip](https://github.com/user-attachments/files/16623894/AnvilGUi.zip)
> 

Will take a look at this soon and update you.

**Comment by JellyBubb1e** [comment]
Any news?
WesJD/AnvilGUI#342

**Comment by CaesarGalahad** [comment]
> Any news? [WesJD/AnvilGUI#342](https://github.com/WesJD/AnvilGUI/issues/342)

As expected, professional matters should still be entrusted to professionals
Thank you

**Comment by Dere-Wah** [comment]
Can you confirm that this new release works?

https://github.com/Dere-Wah/Skript-AnvilGUI/releases/tag/1.9

**Comment by CaesarGalahad** [comment]
Yes, it works
