### ISSUE TITLE
Bug: event-anvil gui

### ISSUE THREAD

**Issue by limegreenicy** [DereWah/Skript-AnvilGUI#2]
Whenever I use "event-anvil gui" in "on anvil gui click:" it gives the following error:

There's no types.anvil in an on on anvilgui click event

As per the documentation I also tested it with this:
```
on anvil gui click:
  if event-integer is 2:
    if title of event-anvil gui is "&0Insert password":
      if event-text is "1234":
        close player's inventory
        send message "&aCorrect password."
      else:
        set text of event-anvil gui to "Wrong password"
        open anvil gui event-anvil gui to player
```
![image](https://github.com/DereWah/Skript-AnvilGUI/assets/36058574/bfbbcda2-1dce-4a65-b6eb-0aa30a6f0264)

**Comment by DereWah** [comment]
It's a known issue, it has to do with the version 2.7 of Skript. Can you try downgrading to 2.6.x and let me know if it works?

**Comment by limegreenicy** [comment]
Ah okay, my bad! I downgraded and it works. Thank you :)
