### ISSUE TITLE
Update 1.20.1

### ISSUE THREAD

**Issue by sluhtie** [DereWah/Skript-AnvilGUI#3]
Hello, please update this addon to 1.20.1

**Comment by DereWah** [comment]
> Hello, please update this addon to 1.20.1

Will update it in the next few days!

**Comment by DereWah** [comment]
Currently running a 1.20.1 server with Skript Anvil GUI and Skript 2.6.4: it's not giving any errors.

**Comment by DereWah** [comment]
Update: I can reproduce the bug and I see it is not working. Will fix

**Comment by sluhtie** [comment]
You just need to update the packages from AnvilGUI api. Did it myself already but thanks :)

**Comment by DereWah** [comment]
> You just need to update the packages from AnvilGUI api. Did it myself already but thanks :)

Yeah, I know. I'm also adding in with this update a fix that makes the addon finally function with Skript 2.7-beta

**Comment by sluhtie** [comment]
Nice :)

**Comment by sluhtie** [comment]
Also why don't you update it to Java 11 or 17 atleast sience you don't support 1.8 anyway

**Comment by DereWah** [comment]
Well, the Addon actually could support 1.8. The thing is Skript 2.6+ doesn't. I prefer keeping a lower java version in the case in the future the SkriptLang team decides to extend compatibility to even older versions. Really unlikely, but who knows
