### ISSUE TITLE
Title syntax issue

### ISSUE THREAD

**Issue by ImNotStable** [DereWah/Skript-AnvilGUI#5]
![image](https://github.com/DereWah/Skript-AnvilGUI/assets/51060503/1c22c65e-f09e-4049-b35c-5a5bc863a801)

on anvil gui click:
  title of event-anvil gui is {@title}
  if event-integer is 2:
  
My plugins: FastAsyncWorldEdit, LuckPerms, PlugManX, SkBee, SkQuery, skRayFall, Skript, *Skript-AnvilGUI, skript-gui, skript-reflect, spark, TabTPS, Vault, ViaBackwards, ViaVersion

Server version: This server is running Paper version git-Paper-17 (MC: 1.20) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: c287e92)

**Comment by DereWah** [comment]
In the latest version there was a syntax change that has yet to make it to the docs.

Use virtual anvil
Instead if anvil gui

So event-virtual anvil should work

**Comment by ImNotStable** [comment]
Thank you
