### ISSUE TITLE
Setting item in anvil gui click event not working

### ISSUE THREAD

**Issue by ImNotStable** [DereWah/Skript-AnvilGUI#6]
```
broadcast "3"
set right item of event-virtual anvil to barrier named "&0"
wait 10 ticks
set right item of event-virtual anvil to air
broadcast "4"
```
3 & 4 are broadcasted in the chat, the anvil isn't changing though, setting the text isn't working either.

My plugins: FastAsyncWorldEdit, LuckPerms, PlugManX, SkBee, SkQuery, skRayFall, Skript, *Skript-AnvilGUI, skript-gui, skript-reflect, spark, TabTPS, Vault, ViaBackwards, ViaVersion

Server version: This server is running Paper version git-Paper-17 (MC: 1.20) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: c287e92)

**Comment by ImNotStable** [comment]
Not sure if I'm doing something wrong

**Comment by DereWah** [comment]
Not sure if you closed becaude you figured it out, but after changing any item in the virtual anvil you MUST re-open it to display the updated version to the player.
